# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/config/Dockerfile'
        repository: 'backend'
        tags: |
          $(tag)
    - script: |
      displayName: Tag for private registry
        docker tag backend:$(tag) docker.io/songlongtj/backend:$(tag)
        docker ps
    - task: NeuVectorScan@3
      inputs:
        scanType: 'standalone'
        nvContainerRegistry: 'nvlab docker hub'
        nvRepository: 'nvpublic/up'
        nvTag: 'latest'
        containerRegistry: 'lsong docker hub'
        repository: 'songlongtj/alpine'
        tag: '3.10'
        scanLayers: true
        reportJsonOutputPath: '$(Build.SourcesDirectory)/scan_result.json'